name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export PATH="$PATH:/root/.nvm/versions/node/v22.2.0/bin/"
            cd /var/apps/ucab-internship-202430
            git restore pnpm-lock.yaml
            git pull
            pnpm install
            pnpm --filter server migration:run
            pnpm build
            pm2 restart movic-backend
            pm2 save
            cp /var/apps/ucab-internship-202430/apps/client/.htaccess /var/apps/ucab-internship-202430/apps/client/dist/client/browser/.htaccess
            rm /var/www/ucab-internship-client -rf
            mv /var/apps/ucab-internship-202430/apps/client/dist /var/www/ucab-internship-client
            cp /var/apps/ucab-internship-202430/apps/client/secrets.js /var/www/ucab-internship-client/client/browser/secrets.js

          # pnpm generate:docs
          # rm /var/www/green-summary-client-docs -rf
          # rm /var/www/green-summary-server-docs -rf
          # mv /var/apps/green-summary-202425/apps/client/documentation /var/www/green-summary-client-docs
          # mv /var/apps/green-summary-202425/apps/server/documentation /var/www/green-summary-server-docs
